name: Test
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.17-alpine
    services:
      mongo:
        image: mongo:5.0.4
        ports:
          - 27017:27017
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: "1.17"
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          go mod download
      - name: Run Unit tests
        run: |
          CGO_ENABLED=0 go test -covermode atomic -coverprofile=covprofile ./...
      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=covprofile -service=github
